### ISSUE TITLE
最后的ｇｎ步骤迭代多次是不是会更精确

### ISSUE THREAD

**Issue by KHuang724** [LIAS-CUHKSZ/CPnP-A-Consistent-PnP-Solver#3]
nice job!
目前我在仿真数据的结果远好于epnp,综合优于mlpnp。
但我看最后的结果中gn只迭代了一次，用每次迭代出的r和t作为初值再多迭代几次是不是效果更好呢，计算量会上升很多吗
谢谢～

**Comment by guangyangzeng** [comment]
谢谢你的评价。在点数够多的时候（比如大于100个点），一步GN迭代后MSE就能达到理论性能下界CRLB，不需要多步GN迭代。当点数较少的时候，GN迭代没法保证精度一定能提升，你可以尝试下迭代个2-3次（没必要太多），看看计算耗时和精度的变化。欢迎再交流~

**Comment by KHuang724** [comment]
没问题的，谢谢！
